function msgComp = canMsgDef_Conti_ARS408()
%CANMSGDEF_CONTI_ARS408		Continental ARS 408 CAN message definition.
%   
%	MSGCOMP = CANMSGDEF_CONTI_ARS408() returns the CAN message definition
%	for the Continental ARS 408 radar sensor.
% 
%	Source: DBC file "ARS408_can_database_ch0 ID 0 only.dbc" parsed using
%	CANdb Editor 3.2.

msgComp = [...
	%
	CANMsgDef('0x060A','Object_0_Status',[...
	CANMsgSignal('Obj_NofObjects',			25, 08, 'U', 'MB', 0, 1, ''),...
	CANMsgSignal('Obj_MeasCounter',			09, 16, 'U', 'MB', 0, 1, ''),...
	CANMsgSignal('Obj_InterfaceVersion',	05, 04, 'U', 'MB', 0, 1, ''),...
	]);...
	%
	CANMsgDef('0x060B','Object_1_General',[...
	CANMsgSignal('Obj_ID',		 57, 08, 'U', 'MB',		 0, 1, '-'),...
	CANMsgSignal('Obj_DistLong', 44, 13, 'U', 'MB', -500.0, 0.2, 'm'),...
	CANMsgSignal('Obj_DistLat',  33, 11, 'U', 'MB', -204.6, 0.2, 'm'),...
	CANMsgSignal('Obj_VrelLong', 23, 10, 'U', 'MB', -128.0, 0.25, 'm/s'),...
	CANMsgSignal('Obj_VrelLat',  14, 09, 'U', 'MB', -64.00, 0.25, 'm/s'),...
	CANMsgSignal('Obj_DynProp',  09, 03, 'U', 'MB',		 0, 1, ''),...
	CANMsgSignal('Obj_RCS',		 01, 08, 'U', 'MB', -64.00, 0.5, 'dBm²'),...
	]);...
	%
	CANMsgDef('0x060C','Object_2_Quality',[...
	CANMsgSignal('Obj_ID',				49, 08, 'U', 'MB', 0, 1, ''),...
	CANMsgSignal('Obj_DistLong_rms',	44, 05, 'U', 'MB', 0, 1, 'm'),...
	CANMsgSignal('Obj_DistLat_rms',		39, 05, 'U', 'MB', 0, 1, 'm'),...
	CANMsgSignal('Obj_VrelLong_rms',	34, 05, 'U', 'MB', 0, 1, 'm/s'),...
	CANMsgSignal('Obj_VrelLat_rms',		29, 05, 'U', 'MB', 0, 1, 'm/2'),...
	CANMsgSignal('Obj_ArelLong_rms',	24, 05, 'U', 'MB', 0, 1, 'm/s²'),...
	CANMsgSignal('Obj_ArelLat_rms',		19, 05, 'U', 'MB', 0, 1, 'm/s²'),...
	CANMsgSignal('Obj_Orientation_rms',	14, 05, 'U', 'MB', 0, 1, ''),...
	CANMsgSignal('Obj_ProbOfExist',		06, 03, 'U', 'MB', 0, 1, ''),...
	CANMsgSignal('Obj_MeasState',		02, 03, 'U', 'MB', 0, 1, ''),...
	]);...
	%
	CANMsgDef('0x060D','Object_3_Extended',[...
	CANMsgSignal('Obj_ID',					57, 08, 'U', 'MB', 0, 1.00, ''),...
	CANMsgSignal('Obj_ArelLong',			46, 11, 'U', 'MB', -10, .01, 'm/s²'),...
	CANMsgSignal('Obj_ArelLat',				37, 09, 'U', 'MB', -2.5, .01, 'm/s²'),...
	CANMsgSignal('Obj_Class',				33, 03, 'U', 'MB', 0, 1.0, ''),...
	CANMsgSignal('Obj_OrientationAngle',	23, 10, 'U', 'MB', -180, 0.4, ''),...
	CANMsgSignal('Obj_Length',				09, 08, 'U', 'MB', 0, 0.2, 'm'),...
	CANMsgSignal('Obj_Width',				01, 08, 'U', 'MB', 0, 0.2, 'm'),...
	]);...
	%
	CANMsgDef('0x060E','Object_4_Warning',[...
	CANMsgSignal('Obj_ID',						25, 08, 'U', 'MB', 0, 1, 'm'),...
	CANMsgSignal('Obj_CollDetRegionBitfield',	16, 08, 'U', 'MB', 0, 1, 'm'),...
	]);...
	];

end%fcn
